### ISSUE TITLE
Fire on page load (suggestion)

### ISSUE THREAD

**Issue by EdCharbeneau** [zurb/reveal#16]
I have an need to fire a model upon page load. So I added the following code to my page:

 //auto trigger modal on page load
    $(document).ready(function () {
        $('[data-reveal-onready]').reveal();
    });

If there is any element on the page with the attribute 'data-reveal-onready' reveal is automatically fired when the page is ready.

While this works great for my needs, others might like something similar "out of the box" especially if you could add a time delay.

**Comment by mkelly12** [comment]
Not a bad idea for the next release.

**Comment by Braunson** [comment]
Already trying to do this :)

**Comment by lukealford** [comment]
this feature is very needed =)

**Comment by jscharf1904** [comment]
simple workaround to get this solved in an easy, uncomlicated way :)

append an ID to the link, the reveal should fired with, f.e. id="popup"

$(function() {
     $('#popup').click();
});

and if the link should be invisible, just add an inline style, f.e. 
style="hidden"

works fine :)

**Comment by Ethanhackett** [comment]
The custom function worked for me. I'm using it on a registration form. And I needed it to default to load if there's an error message. Though it might be a nice feature to simply toggle a class instead of adding additional javascript on the page. But for not it only happens on the homepage and seems to work well enough. Thanks @jscharf1904!
