### ISSUE TITLE
w3C validation

### ISSUE THREAD

**Issue by dojodesign** [zurb/reveal#5]
First off, love this plugin!

I have a client who wishes to use it but needs to have a w3c validated site. Only thing that stops this from happening if the following ID tag: 'data-reveal-id'.

Is their anyway to change this just to 'id' so it can validate?

Hope you can help.

Chris

**Comment by mkelly12** [comment]
Are you using a HTML5 doc type? The W3C validator will accept data dash (data-variablename) attributes since they are part of the HTML5 spec, assuming you tell it validate as HTML5 markup.

We like the data dash attributes a lot for plugins because they allow people to configure the plugin right from the markup, without expecting that people will be able to change the values of existing attributes.

**Comment by dojodesign** [comment]
ahh of course. That sorted it.

Cheers!
